#+Title: Rails and Phoenix Side-by-Side
#+Author: Scott Smith (OldFartDeveloper)
#+Email: scottnelsonsmith@gmail.com

* Introduction

Tonight:

  - Introduce *Elixir* / *Phoenix*

  - Build a *Phoenix* web app with authentication

  - Discuss development environment

* Elixir / Phoenix

  - Elixir :: A syntactically-rich functional language that transpiles to Erlang,
              a mature ultra-reliable language and library that's been developed
              ove the last 30 years.
  - Phoenix :: A web framework implemented in Elixir and patterned liked Rails.

** Elixir

    - Syntax is not Ruby but feels like it.
    - Like Ruby, has powerful metaprogramming capability.

** Phoenix

  - Patterned after Rails
    - Model/View/Controller
    - Migrations
    - Scaffolding
    - Console

** Erlang

Powerful

* The End!

Well there we have it. It wasn't so bad was it? Let me know what you think in the commments! Thank you so much for taking the time to read this and I hope you've learned something!
* Play Area

Nice org mode commands from Forrest.  Just type them as /less-than/ then one of:

  - 's' for code blocks ("source" code)
  - 'q' for quote
  - 'h' for html block

#+BEGIN_QUOTE
Everything should be made as simple as possible,
     but not any simpler -- Albert Einstein
#+END_QUOTE
And let's see what that does.
#+BEGIN_HTML
<h3>A header</h3>
<p>Here is a paragraph</p>
#+END_HTML
#+REVEAL: split
#+BEGIN_SRC ruby
def bun
  # do something
end
#+END_SRC
